{
 "title": "Cisco ACI",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "APICCluster",
    "label": "APIC Cluster",
    "query": "SHOW TAG VALUES FROM ACI_APIC WITH KEY=apic"
   }
  ]
 },
 "panels": [
  {
   "title": "System Health - Current",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"fabricHealthTotal_attributes_cur\") FROM \"ACI_SystemHealth\" WHERE (\"apic\" =~ /^$APICCluster$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Critical - Current",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"faultCountsWithDetails_attributes_crit\") FROM \"ACI_Faults\" WHERE (\"apic\" =~ /^$APICCluster$/) AND $timeFilter ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Major - Current",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"faultCountsWithDetails_attributes_maj\") FROM \"ACI_Faults\" WHERE (\"apic\" =~ /^$APICCluster$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Minor - Current",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"faultCountsWithDetails_attributes_minor\") FROM \"ACI_Faults\" WHERE (\"apic\" =~ /^$APICCluster$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Warning - Current",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "measurement": "ACI_Faults",
     "select": [
      [
       {
        "params": [
         "faultCountsWithDetails_attributes_warn"
        ],
        "type": "field"
       }
      ]
     ],
     "tags": [
      { "key": "apic", "operator": "=~", "value": "/^$APICCluster$/" }
     ]
    }
   ]
  },
  {
   "title": "APIC Status",
   "type": "table-old",
   "gridPos": { "h": 4, "w": 9, "x": 15, "y": 0 },
   "targets": [
    {
     "groupBy": [
      {
       "params": [
        "infraWiNode_attributes_nodeName"
       ],
       "type": "tag"
      },
      { "params": [ "infraWiNode_attributes_addr" ], "type": "tag" }
     ],
     "limit": "1",
     "measurement": "ACI_APIC",
     "query": "SELECT \"infraWiNode_attributes_apicMode\" AS \"Mode\", \"infraWiNode_attributes_health\" AS \"Health\", \"infraWiNode_attributes_failoverStatus\" AS \"FailoverStatus\", \"infraWiNode_attributes_adminSt\" AS \"AdminStatus\", \"infraWiNode_attributes_operSt\" AS \"OperStatus\" FROM \"ACI_APIC\" WHERE time = now() -10m ",
     "select": [
      [
       {
        "params": [
         "infraWiNode_attributes_apicMode"
        ],
        "type": "field"
       },
       { "params": [ "Mode" ], "type": "alias" }
      ],
      [
       { "params": [ "infraWiNode_attributes_health" ], "type": "field" },
       { "params": [ "Health" ], "type": "alias" }
      ],
      [
       {
        "params": [
         "infraWiNode_attributes_failoverStatus"
        ],
        "type": "field"
       },
       { "params": [ "FailoverStatus" ], "type": "alias" }
      ],
      [
       { "params": [ "infraWiNode_attributes_adminSt" ], "type": "field" },
       { "params": [ "AdminStatus" ], "type": "alias" }
      ],
      [
       { "params": [ "infraWiNode_attributes_operSt" ], "type": "field" },
       { "params": [ "OperStatus" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "System Health",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ACI_SystemHealth",
     "select": [
      [
       {
        "params": [
         "fabricHealthTotal_attributes_cur"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Current" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "apic", "operator": "=~", "value": "/^$APICCluster$/" }
     ]
    }
   ]
  },
  {
   "title": "System Faults",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ACI_Faults",
     "select": [
      [
       {
        "params": [
         "faultCountsWithDetails_attributes_crit"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "critical" ], "type": "alias" }
      ],
      [
       {
        "params": [
         "faultCountsWithDetails_attributes_maj"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "major" ], "type": "alias" }
      ],
      [
       {
        "params": [
         "faultCountsWithDetails_attributes_minor"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "minor" ], "type": "alias" }
      ],
      [
       {
        "params": [
         "faultCountsWithDetails_attributes_warn"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "warning" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "apic", "operator": "=~", "value": "/^$APICCluster$/" }
     ]
    }
   ]
  },
  { "title": "Tenant", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Tenant Health",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "fvTenant_attributes_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ACI_TenantHealth",
     "select": [
      [
       {
        "params": [
         "fvTenant_children_0_healthInst_attributes_cur"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "H" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "apic", "operator": "=~", "value": "/^$APICCluster$/" }
     ]
    }
   ]
  },
  {
   "title": "Infra - Current",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 12 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "ACI_TenantHealth",
     "select": [
      [
       {
        "params": [
         "fvTenant_children_0_healthInst_attributes_cur"
        ],
        "type": "field"
       },
       { "params": [ "Current" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "fvTenant_attributes_name", "operator": "=", "value": "infra" },
      { "condition": "AND", "key": "apic", "operator": "=~", "value": "/^$APICCluster$/" }
     ]
    }
   ]
  },
  {
   "title": "Common - Current",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 12 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "ACI_TenantHealth",
     "select": [
      [
       {
        "params": [
         "fvTenant_children_0_healthInst_attributes_cur"
        ],
        "type": "field"
       },
       { "params": [ "Current" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "fvTenant_attributes_name", "operator": "=", "value": "common" },
      { "condition": "AND", "key": "apic", "operator": "=~", "value": "/^$APICCluster$/" }
     ]
    }
   ]
  },
  {
   "title": "Tenant Health",
   "type": "table-old",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 12 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"fvTenant_children_0_healthInst_attributes_cur\") AS \"Health\" FROM \"ACI_TenantHealth\" WHERE (\"apic\" =~ /^$APICCluster$/) AND $timeFilter GROUP BY \"fvTenant_attributes_name\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Tenant Count - Current",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 16 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(*) FROM(SELECT last(\"fvTenant_children_0_healthInst_attributes_cur\") AS \"Health\" FROM \"ACI_TenantHealth\" WHERE (\"apic\" =~ /^$APICCluster$/) AND time > now() - 3m GROUP BY \"fvTenant_attributes_name\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Node", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Node Health",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "topSystem_attributes_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ACI_NodeHealth",
     "select": [
      [
       {
        "params": [
         "topSystem_children_0_healthInst_attributes_cur"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Current" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "apic", "operator": "=~", "value": "/^$APICCluster$/" }
     ]
    }
   ]
  },
  {
   "title": "Node Status",
   "type": "table-old",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 20 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"topSystem_attributes_state\") AS \"state\", \"topSystem_attributes_systemUpTime\" AS \"UpTime\", \"topSystem_children_0_healthInst_attributes_cur\" AS \"Health\" FROM \"ACI_NodeHealth\" WHERE (\"apic\" =~ /^$APICCluster$/) AND $timeFilter GROUP BY \"topSystem_attributes_name\", \"topSystem_attributes_oobMgmtAddr\", \"topSystem_attributes_podId\", \"topSystem_attributes_role\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}